### ISSUE TITLE
empty folders in Release 19.0.6

### ISSUE THREAD

**Issue by immwi** [24u/fmRESTor.php#3]
Hi, the "binaries" in release 19.0.6 contain nothing. there are empty folders. thanks.

**Comment by filip24u** [comment]
Hello immwi,

thank you for letting me know about this problem. I find out this problem is on signpost ( https://github.com/24u/fmRESTor ). Have you noticed this problem anywhere other than just on signpost ?

These links should be working correctly:
“PHP” Version can be found here: https://github.com/24u/fmRESTor.php
“JS” Version can be found here: https://github.com/24u/fmRESTor.js

Have a nice day,
Filip

**Comment by immwi** [comment]
Hi Filip

Thank you. No it's indeed on https://github.com/24u/fmRESTor/releases/tag/19.0.6  when you click the zip for download, unzip it and then look into the folders. they are empty.

cheers
Immanuel

**Comment by filip24u** [comment]
Hi Immanuel,

after some reserch it's looks like standard github/git behaviour that folders are empty, because signpost "fmRESTor" ( https://github.com/24u/fmRESTor ) has connected two "Submodules":

https://github.com/24u/fmRESTor.js
https://github.com/24u/fmRESTor.php

Github/git in the default state doesn't download these submodules. 

The one of the way how to solve that is avoid Download button in Github and clone repository by command line:

`git clone https://github.com/24u/fmRESTor.git --recursive`

But in my opinion repositories for PHP and JS should be sufficient:

https://github.com/24u/fmRESTor.js
https://github.com/24u/fmRESTor.php

Have a nice day,
Filip
